apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-httpd
  namespace: openshift-gitops
spec: 
  destination: 
    namespace: art-eazytraining
    server: 'https://kubernetes.default.svc'
  project: default
  source: 
    path: config/overlays/dev
    repoURL: https://github.com/ObieBent/eazytraining-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true