apiVersion: v1 
kind: Secret
metadata: 
  name: git-ssh-key
  namespace: ${NAMESPACE}
  annotations: 
    tekton.dev/git-0: ${GITLAB_HOST_FQDN}
  type: kubernetes.io/ssh-auth
data: 
  ssh-privatekey: ${BASE64_PRIVATE_SSH_KEY}