apiVersion: template.openshift.io/v1
kind: Template
labels:
  build-template: devops_openshift-simple-route-template-route
message: "Simple Route template for Eazytraining simple-route-template"
metadata:
  annotations:
    description: "Simple Deploy template for Eazytraining simple-route-template"
  name: eazytraining_openshift-simple-route-template
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: app-${APPLICATION_NAME}
      name: route-${APPLICATION_NAME}
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: svc-${APPLICATION_NAME}
        weight: 100
parameters:
  - name: APPLICATION_NAME
    value: eazytraining-httpd
    required: true
