apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: sample-httpd-pipeline
  namespace: ${NAMESPACE}
spec:
  tasks: 
  - name: fetch-source
    params: 
    - name: url 
      description: The git repository url
      value: '${REPO_GIT_URL}'
    - name: revision
      description: The git revision
      value: ${REPO_GIT_BRANCH}
    taskRef: 
      kind: ClusterTask
      name: git-clone
    workspaces: 
    - name: output 
      workspace: source-dir
    - name: ssh-directory
      workspace: git-credentials
  - name: build-and-push-image
    params:
    - name: CONTEXT
      value: "cicd/s2i/sample-app-httpd/docker"
    - name: IMAGE
      value: >-
        image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/dck_eazytraining-lab-http:latest
    runAfter: 
    - fetch-source
    taskRef:
      kind: ClusterTask
      name: buildah 
    workspaces: 
    - name: source
      workspace: source-dir
  workspaces:
    - name: source-dir
    - name: git-credentials