apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitops-dev-pipeline
spec:
  params:
    - default: 'http://gitlab.eazytraining.lab/boass/eazytraining.git'
      description: Source to the GIT
      name: git-url
      type: string
    - default: main
      description: revision to be used
      name: git-revision
      type: string
    - name: config-git-url
      type: string
      description: URL of the Git config repository
      default: 'http://gitlab.eazytraining.lab/boass/eazytraining-config.git'
    - name: config-dir
      type: string
      description: Configuration directory within the config-git-url with the files
      default: 'config/overlays/dev'
    - name: context-dir
      default: "the-source"
      type: string
      description: Where to checkout the source relative to the workspace
    - name: image-name
      type: string
      description: the name of the target image including registry
      default: quay.io/wpernath/quarkus-simple-wow
    - name: image-username
      type: string
      description: the username you use to access the registry
    - name: image-password
      type: string
      description: The password you use to access the registry
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.context-dir)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: git-credentials
    - name: build-and-push-image
      params:
        - name: CONTEXT
          value: "cicd/s2i/sample-app-httpd/docker"
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah 
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: extract-digest
      params:
        - name: image-digest-path
          value: $(params.context-dir)/target
      runAfter:
        - build-and-push-image
      taskRef:
        kind: Task
        name: extract-sample-httpd-digest
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: git-update-deployment
      params:
        - name: GIT_REPOSITORY
          value: $(params.config-git-url)
        - name: CURRENT_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/eazytraining/dck_eazytraining-lab-http:latest
        - name: NEW_IMAGE
          value: $(params.image-name)
        - name: NEW_DIGEST
          value: $(tasks.extract-digest.results.DIGEST)
        - name: KUSTOMIZATION_PATH
          value: $(params.config-dir)
      runAfter:
        - extract-digest
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: workspace
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      optional: false
    - name: git-credentials
      optional: false