apiVersion: v1 
kind: Secret
metadata: 
  name: ssh-key
  annotations: 
    tekton.dev/git-0: ${GITLAB_HOST_FQDN}
  type: kubernetes.io/ssh-auth
  stringData: 
    ssh-privatekey: ${BASE64_PRIVATE_SSH_KEY}