apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: sample-httpd-pipeline
spec:
  tasks: 
  - name: fetch-source
    params: 
    - name: url 
      value: '${REPO_GIT_URL}'
    - name: revision
      value: ${REPO_GIT_BRANCH}
    taskRef: 
      kind: ClusterTask
      name: git-clone
    workspaces: 
    - name: output 
      workspace: source-dir
  - name: build-and-push-image
    params:
    - name: CONTEXT
      value: "apps/sample-app-httpd/docker"
    - name: IMAGE
      value: >-
        image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/dck_eazytraining-lab-http:1.0
    runAfter: 
    - fetch-source
    taskRef:
      kind: ClusterTask
      name: buildah 
    workspaces: 
    - name: source
      workspace: source-dir
  workspaces:
    - name: source-dir    