apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-httpd-pipeline-run 
  namespace: ${NAMESPACE}
spec:
  pipelineRef:
    name: sample-httpd-pipeline
  workspaces:
  - name: source-dir
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credentials
    secret:
      secretName: ssh-key