apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: app-eazytraining
  name: route-eazytraining-httpd
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: svc-eazytraining-httpd
    weight: 100