apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: sample-httpd-listener
  namespace: eazytraining
spec: 
  serviceAccountName: pipeline 
  triggers: 
  - bindings: 
    - kind: ClusterTriggerBinding 
      ref: gitlab-push 
    name: trigger-1
    template: 
      ref: sample-httpd-trigger