apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sample-httpd-trigger
  namespace: eazytraining
spec: 
  params: 
  - default: main
    name: revision
  - default: 'http://gitlab.eazytraining.lab/boass/eazytraining.git'
    name: url
  resourcetemplates: 
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: sample-httpd-pipeline-run-
    spec: 
      pipelineRef:
        name: gitops-dev-pipeline
      serviceAccountName: pipeline-bot 
      workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
           claimName: builder-pvc
      - name: git-credentials
        secret:
          secretName: git-ssh-key