apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sample-httpd-trigger
  namespace: eazytraining
spec: 
  params: 
  - default: main
    name: revision
  - default: 'http://gitlab.eazytraining.lab/boass/eazytraining.git'
    name: url
  resourcetemplates: 
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: sample-httpd-pipeline-run-
    spec: 
      pipelineRef:
        name: sample-httpd-pipeline
      serviceAccountName: pipeline 
      workspaces:
      - name: source-dir
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      - name: git-credentials
        secret:
          secretName: git-ssh-key