apiVersion: template.openshift.io/v1
kind: Template
labels: 
  build-template: dck_image-template 
message: "Build template for Eazytraining dck_image-template"
metadata: 
  annotations: 
    description: "Build template for Eazytraining dck_image-template"
  name: dck_image-template 
objects: 
  - apiVersion: v1 
    kind: BuildConfig 
    metadata: 
      labels: 
        app: dck-${IMAGE_NAME}-${IMAGE_TAG}
      name: dck-${IMAGE_NAME}-${IMAGE_TAG}
    spec: 
      completionDeadlineSecond: 1800
      failedBuildsHistoryLimit: 3
      successfulBuildsHistoryLimit: 2
      output:
        to:
          kind: ImageStreamTag
          name: dck_${IMAGE_NAME}:${IMAGE_TAG}
      source: 
        git:
          ref: "${GIT_BRANCH}"
          uri: ${GIT_URL}
        type: Git
        contextDir: "apps/sample-app-httpd/docker"
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile
          forcePull: true
          noCache: true
          from:
            kind: ImageStreamTag
            name: ${FROM_IMAGE}
            namespace: ${FROM_NAMESPACE}
        type: Docker
      triggers:
        - imageChange:
          type: ImageChange
parameters:       
  - name: IMAGE_NAME
    description: Name of the image
    value: "eazytraining-lab-http" 
    required: true
  - name: GIT_BRANCH
    description: Source Repository branch 
    value: "main" 
    required: true
  - name: IMAGE_TAG
    description: Image Tag
    value: "1.0"
    required: true
  - name: GIT_URL
    description: Source Repository URL
    value: "https://github.com/ObieBent/eazytraining.git" 
    required: true
  - name: FROM_NAMESPACE
    description: Source namespace
    value: "openshift"
    required: true
  - name: FROM_IMAGE
    description: Source image 
    value: "httpd:2.4-el7" 
    required: true