apiVersion: template.openshift.io/v1
kind: Template
labels:
  build-template: devops_openshift-simple-dc-template-deploymentconfig
message: "Simple DeploymentConfig template for Eazytraining simple-dc-template"
metadata:
  annotations:
    description: "Simple DeploymentConfig template for Eazytraining simple-dc-template"
  name: devops_openshift-simple-dc-template
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: app-${APPLICATION_NAME}
      name: dc-${APPLICATION_NAME}
    spec:
      revisionHistoryLimit: 5
      replicas: 2
      selector:
        app: app-${APPLICATION_NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 50%
          maxUnavailable: 50%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: app-${APPLICATION_NAME}
            deploymentconfig: dc-${APPLICATION_NAME}
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - app-${APPLICATION_NAME}
                    topologyKey: site
                  weight: 100
          containers:
            - volumeMounts:
              - mountPath: /run/httpd/
                name: pid-dir
              - mountPath: /etc/httpd/logs/
                name: log-dir
              name: ${APPLICATION_NAME}
              livenessProbe:
                exec:
                  command:
                    - /usr/bin/pgrep
                    - httpd
                failureThreshold: 3
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - /usr/bin/pgrep
                    - httpd
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 250m
                  memory: 250Mi
                requests:
                  cpu: 250m
                  memory: 250Mi
              image: ${FROM_IMAGE}
              securityContext:
                readOnlyRootFilesystem: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: pid-dir
            - emptyDir: {}
              name: log-dir
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APPLICATION_NAME}
            from:
              kind: ImageStreamTag
              name: ${FROM_IMAGE}
              namespace: ${FROM_NAMESPACE}
          type: ImageChange
parameters:
  - name: FROM_NAMESPACE
    value: "eazytraining"
    required: true
  - name: FROM_IMAGE
    description: Source image 
    value: "dck_eazytraining-lab-http:1.0" 
    required: true
  - name: APPLICATION_NAME
    value: "eazytraining-httpd"
    required: true
