parameters:
  IMAGE_NAME: "eazytraining-lab-http"
  IMAGE_TAG: "1.0"
  FROM_IMAGE: "httpd:2.4-el7"
  FROM_NAMESPACE: "openshift"
  GIT_URL: "https://github.com/ObieBent/eazytraining/apps/sample-app-httpd"
  GIT_BRANCH: "main"
  VERSION: "1.0"
  APPLICATION_NAME: "eazytraining-httpd"
  EXTERNAL_HOST: "eazytraining-httpd.apps.caas.eazytraining.lab" 
