apiVersion: template.openshift.io/v1 
kind: Template
labels:
  build-template: devops_openshift-simple-deploy-template-service
message: "Simple Deploy template for Eazytraining simple-deploy-template"
metadata:
  annotations:
    description: "Simple Deploy template for Eazytraining simple-deploy-template" 
  creationTimestamp: null
  name: eazytraining_openshift-simple-service-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: app-${APPLICATION_NAME}
      name: svc-${APPLICATION_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8443-tcp
          port: 8443
          protocol: TCP
          targetPort: 8443
      selector:
        app: app-${APPLICATION_NAME}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
parameters:
  - name: APPLICATION_NAME
    required: true
    value: "eazytraining-httpd"